# Generated by Django 4.0.6 on 2022-07-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place1', models.CharField(max_length=100)),
                ('place2', models.CharField(max_length=100)),
                ('place3', models.CharField(max_length=100)),
                ('place4', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.document')),
            ],
        ),
    ]
